### ISSUE TITLE
Extract a separate analyzer from the compiler

### ISSUE THREAD

**Issue by lucifer1004** [lucifer1004/MonkeyLang.jl#16]
Currently, the evaluator detects some semantic errors (e.g., variable redefinition) during evaluation, while the Julia transpiler completely ignores these errors.

@c42f provides a great idea, that is to separate the semantic analysis from the compiler so that it can be reused by the evaluator and transpiler.

This will also help lay a foundation for the type system.

**Comment by c42f** [comment]
Cool. By the way if you like compiler frontends, you might be interested in looking at the one I'm writing right now:
https://github.com/c42f/JuliaSyntax.jl

**Comment by lucifer1004** [comment]
Thanks for the reference.

**Comment by lucifer1004** [comment]
Closed by #24
